## Parte 1. Conceptos

Responde con tus palabras en esta seccion o en una celda Markdown de tu notebook.

1. Que es aprendizaje supervisado?
2. Que es una variable objetivo?
3. Que significa `venta_alta`?
4. Que diferencia hay entre `X` e `y`?
5. Que es clasificacion?
6. Por que este problema es de clasificacion?
7. Que hace `DecisionTreeClassifier`?
8. Para que sirve separar entrenamiento y prueba?
9. Que significa exactitud?
10. Para que sirve una matriz de confusion?
11. Que significa `fit()`?
12. Que significa `predict()`?
13. Por que se usa `pd.get_dummies()`?
14. Por que se usa `reindex()` al predecir ventas nuevas?
15. Por que una prediccion no es una verdad absoluta?

### Respuestas Del Estudiante

Escribe aqui tus respuestas:

```text
1. Es el entrenamiento y predicción de respuestas en base a un conjunto de datos de entrada, al momento de entrenar se le dan las respuestas al modelo y en base a eso se entrena el modelo
2. Es la variable que el modelo intentará predecir
3. Es una variable booleana que define si una venta está por encima de cierto umbral
4. X son las variables de entrada o predictorias sobre las que el modelo se basará, y es la variable objetivo que el modelo predecirá
5. Es la categorización de un conjunto de variables de entrada, para hacer una salida en categorías o etiquetas ya definidas
6. Porque se intenta predecir en base al conjunto de datos si esa venta fue baja o alta
7. Es un arbol de decisiones que va haciendo preguntas tipo true/false hasta dar en un resultado
8. El entrenamiento sirve para que el modelo pueda basarse en eso y así predecir el resultado, la prueba es para que el modelo pueda probar el entrenamiento y ver la exactitud y precision
9. Es la cantidad de valores predecidos correctamente
10. Para poder ver todos los valores, siendo estos los correctos, falsos, falsos positivos y falsos negativos
11. fit() significa meter los datos al modelo y hace que este entrene en base a estos
12. predict(nuevos_valores) es para poder predecir los nuevos resultados en base a lo entrenado
13. Para evitar que haya texto en las filas, ya que un modelo no entiende texto sino números. get dummies crea tantas columnas como valores de texto distintos haya
14. Para que los datos que se vayan a predecir tengan las mismas columnas que con los que se entrenó el modelo. reindex() elimina las columnas extra y llena con 0 todas las que no estén presentes
15. Porque siempre se pueden agregar más textos, que implica más columnas. Esto y varios factores más (uno de ellos la exactitud) hacen que un modelo realmente no esté correcto siempre, solo sea una predicción probable que puede estar mal
```

## Parte 2. Revision Del Dataset

Carga el dataset con pandas.

Realiza lo siguiente:

1. Muestra las primeras filas.
2. Revisa las columnas.
3. Muestra cuantas filas y columnas tiene.
4. Revisa si hay valores nulos.
5. Verifica que exista la columna `total_venta`.
6. Verifica que `total_venta` coincida con `cantidad * precio_unitario`.
7. Escribe una observacion breve sobre el estado del dataset.

In [1]:
# Carga el dataset con pandas.
import pandas as pd
df = pd.read_csv("ventas_ecommerce_limpio.csv")

In [2]:
# 1. Muestra las primeras filas.
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

In [3]:
# 2. Revisa las columnas.
df.columns.tolist()

['id_venta',
 'fecha',
 'cliente',
 'producto',
 'categoria',
 'cantidad',
 'precio_unitario',
 'metodo_pago',
 'ciudad',
 'total_venta']

In [4]:
# 3. Muestra cuantas filas y columnas tiene.
df.shape

(60, 10)

In [5]:
# 4. Revisa si hay valores nulos.
df.isnull().sum()

id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64

In [6]:
# 5. Verifica que exista la columna `total_venta`.
df["total_venta"].head()

0    250.0
1    650.0
2    900.0
3    800.0
4    360.0
Name: total_venta, dtype: float64

In [7]:
# 6. Verifica que `total_venta` coincida con `cantidad * precio_unitario`.
df["total_calculado"] = df["cantidad"] * df["precio_unitario"]
df[df["total_venta"] != df["total_calculado"]]

Empty DataFrame
Columns: [id_venta, fecha, cliente, producto, categoria, cantidad, precio_unitario, metodo_pago, ciudad, total_venta, total_calculado]
Index: []

# 7. Escribe una observacion breve sobre el estado del dataset.
# El dataset actual se encuentra limpio y correcto para iniciar el entrenamiento del modelo

## Parte 3. Variable Objetivo

Crea la columna:

```text
venta_alta
```

Regla:

```text
Si total_venta >= 1000, venta_alta = 1
Si total_venta < 1000, venta_alta = 0
```

Indicaciones:

1. Puedes usar una funcion normal o una lambda.
2. Cuenta cuantas ventas quedaron como 1 y cuantas como 0.

Pregunta obligatoria:

```text
Por que venta_alta es la variable objetivo?
```

In [8]:
df["venta_alta"] = df["total_venta"].apply(lambda x: 1 if x >= 1000 else 0)

In [9]:
df["venta_alta"].value_counts()

venta_alta
1    40
0    20
Name: count, dtype: int64

¿Por que venta_alta es la variable objetivo?
Porque es una variable booleana que representa una etiqueta o categoría. Si no es 1, es 0

## Parte 4. Variables De Entrada

Usa como variables de entrada:

```text
cantidad
precio_unitario
categoria
metodo_pago
ciudad
```

Usa como variable objetivo:

```text
venta_alta
```

Indicaciones:

1. Crea `X`.
2. Crea `y`.
3. Convierte variables categoricas con `pd.get_dummies()`.
4. Guarda la lista de columnas generadas.
5. Muestra las primeras filas de `X` despues de `get_dummies()`.

Pregunta obligatoria:

```text
Por que no se debe usar total_venta como variable de entrada si venta_alta se creo a partir de total_venta?
```

In [10]:
X = df[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [11]:
y = df["venta_alta"]

In [12]:
X = pd.get_dummies(X)

In [13]:
columnas_modelo = X.columns.tolist()

Por que no se debe usar total_venta como variable de entrada si venta_alta se creo a partir de total_venta?
Porque la variable objetivo sale directamente de ella. Es posible que el modelo simplemente haga la pregunta si total venta es mayor a 1000, perdiendo el propósito como modelo predictivo

## Parte 5. Entrenamiento Y Evaluacion

Entrena un modelo con `DecisionTreeClassifier`.

Indicaciones:

1. Divide los datos en entrenamiento y prueba.
2. Usa 80% entrenamiento y 20% prueba.
3. Usa `random_state=42`.
4. Entrena el modelo.
5. Genera predicciones con los datos de prueba.
6. Calcula exactitud.
7. Muestra matriz de confusion.
8. Crea una tabla llamada `resultados_prueba` con:

```text
valor_real
prediccion
coincide
```

9. Cuenta cuantos aciertos y cuantos errores hubo.

Preguntas obligatorias:

1. Cual fue la exactitud?
2. Cuantos aciertos tuvo el modelo?
3. Cuantos errores tuvo el modelo?
4. Que indica la matriz de confusion?
5. Una buena exactitud significa que el modelo ya es perfecto? Explica.

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
model = DecisionTreeClassifier(random_state=42)

In [17]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [18]:
y_pred = model.predict(X_test)

In [19]:
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud: ", exactitud)

Exactitud:  1.0

In [20]:
matriz = confusion_matrix(y_test, y_pred, labels=[0, 1])
matriz

array([[4, 0],
       [0, 8]])

In [21]:
resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": y_pred
})

In [22]:
resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

In [23]:
resultados_prueba["coincide"].value_counts()

coincide
True    12
Name: count, dtype: int64

Preguntas obligatorias:

Cual fue la exactitud?
El 100%

Cuantos aciertos tuvo el modelo?
12 de 12

Cuantos errores tuvo el modelo?
0

Que indica la matriz de confusion?
Es un mejor análisis de las respuestas correctas e incorrectas, mostrando también falsos positivos y falsos negativos

Una buena exactitud significa que el modelo ya es perfecto? Explica.
No realmente, porque si llegasen a existir más columnas que se tengan que eliminar, es posible que el modelo baje en su predicción. La exactitud solo nos dice de los datos ya predecidos, no de los datos a predecir

## Parte 6. Guardar Modelo Y Columnas

Guarda:

```text
modelo_examen_venta_alta.pkl
columnas_examen_modelo.pkl
```

Indicaciones:

1. Usa `joblib`.
2. Guarda el modelo entrenado.
3. Guarda la lista de columnas usadas durante el entrenamiento.
4. Verifica que los archivos aparezcan en tu carpeta.

Preguntas obligatorias:

1. Para que sirve guardar el modelo?
2. Para que sirve guardar las columnas del entrenamiento?
3. Que problema puede aparecer si no guardas las columnas?

In [24]:
import joblib

In [25]:
joblib.dump(model, "modelo_examen_venta_alta.pkl")

['modelo_examen_venta_alta.pkl']

In [26]:
joblib.dump(columnas_modelo, "columnas_examen_modelo.pkl")

['columnas_examen_modelo.pkl']

Preguntas obligatorias:

1. Para que sirve guardar el modelo?
Para poder usarlo nuevamente en otra ocasión sin tener que entrenar el modelo

2. Para que sirve guardar las columnas del entrenamiento?
Para saber en base a qué se entrenó el modelo y poder hacer reindex()

3. Que problema puede aparecer si no guardas las columnas?
No se sabría en base a qué predice el modelo y por ende o baja la exactitud o incluso puede fallar

## Parte 7. Ventas Nuevas

Crea un archivo llamado:

```text
examen_ventas_nuevas.csv
```

Debe contener al menos 10 ventas nuevas.

Columnas obligatorias:

```text
id_venta
fecha
cliente
producto
categoria
cantidad
precio_unitario
metodo_pago
ciudad
```

Condiciones obligatorias:

1. Incluye al menos 4 ventas claramente altas.
2. Incluye al menos 4 ventas claramente no altas.
3. Incluye al menos 2 ventas cercanas al limite de 1000.
4. Incluye al menos 1 categoria nueva.
5. Incluye al menos 1 ciudad nueva.
6. No copies exactamente las ventas del pre examen.
7. No uses las mismas ventas que otro companero.

Importante:

El dataset `ventas_ecommerce_limpio.csv` se usa para entrenar.

Tus ventas nuevas son solamente para probar el modelo ya entrenado.


No las agregues al dataset de entrenamiento.

---

## Parte 8. Cargar Modelo Y Predecir

Usa el modelo guardado para predecir tus ventas nuevas.

Indicaciones:

1. Carga `modelo_examen_venta_alta.pkl`.
2. Carga `columnas_examen_modelo.pkl`.
3. Carga `examen_ventas_nuevas.csv`.
4. Selecciona las mismas variables de entrada usadas en entrenamiento.
5. Aplica `pd.get_dummies()`.
6. Alinea columnas con `reindex()`.
7. Genera predicciones.
8. Agrega la columna:

```text
prediccion_venta_alta
```

9. Agrega la columna:

```text
interpretacion_prediccion
```

donde:

```text
0 = Venta no alta
1 = Venta alta
```

10. Guarda el resultado como:

```text
examen_predicciones.csv
```

Pregunta obligatoria:

```text
Que podria pasar si no usas reindex antes de predecir?
```

In [27]:
modelo_cargado = joblib.load("modelo_examen_venta_alta.pkl")
columnas_cargadas = joblib.load("columnas_examen_modelo.pkl")
nuevas_ventas = pd.read_csv("examen_ventas_nuevas.csv")

In [28]:
X_nuevas = nuevas_ventas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [29]:
X_nuevas = pd.get_dummies(X_nuevas)

In [30]:
X_nuevas = X_nuevas.reindex(columns=columnas_cargadas, fill_value=0)

In [31]:
nuevas_ventas["predicciones"] = modelo_cargado.predict(X_nuevas)

In [32]:
nuevas_ventas["prediccion_venta_alta"] = nuevas_ventas["predicciones"].apply(lambda x: "Venta no alta" if x == 0 else "Venta alta")

In [33]:
nuevas_ventas[["predicciones", "prediccion_venta_alta", "precio_unitario", "cantidad"]]

   predicciones prediccion_venta_alta  precio_unitario  cantidad
0             0         Venta no alta           1000.0         3
1             0         Venta no alta           2000.0         2
2             0         Venta no alta            450.0         1
3             0         Venta no alta            400.0         1
4             0         Venta no alta            210.0         5
5             0         Venta no alta           2000.0         2
6             0         Venta no alta            490.0         2
7             1            Venta alta            800.0         4
8             1            Venta alta            220.0         2
9             1            Venta alta            160.0         2

In [34]:
nuevas_ventas.to_csv("examen_predicciones.csv", index=False)

Pregunta obligatoria:

Que podria pasar si no usas reindex antes de predecir?
El modelo predecirá en base a otro conjunto de datos de entrada con el cual no entrenó, bajando la exactitud

## Parte 9. Auditoria Del Modelo

Revisa si las predicciones coinciden con una regla manual.

Indicaciones:

1. Calcula:

```text
total_estimado = cantidad * precio_unitario
```

2. Crea:

```text
venta_alta_real_estimada
```

usando:

```text
Si total_estimado >= 1000, entonces 1
Si total_estimado < 1000, entonces 0
```

3. Compara:

```text
prediccion_venta_alta
venta_alta_real_estimada
```

4. Crea la columna:

```text
coincide
```

5. Cuenta cuantas predicciones coincidieron y cuantas no.
6. Filtra las ventas que no coincidieron.
7. Revisa si los errores estan cerca del limite de 1000.
8. Guarda de nuevo `examen_predicciones.csv` con las columnas de auditoria.

Preguntas obligatorias:

1. Cuantas ventas nuevas evaluaste?
2. Cuantas fueron predichas como venta alta?
3. Cuantas fueron predichas como venta no alta?
4. Cuantas coincidieron con la regla manual?
5. Cuantas no coincidieron?
6. Que ventas no coincidieron?
7. Los errores estuvieron cerca del limite de 1000?
8. Que paso con la categoria nueva?
9. Que paso con la ciudad nueva?

In [35]:
nuevas_ventas["total_estimado"] = nuevas_ventas["cantidad"] * nuevas_ventas["precio_unitario"]

In [36]:
nuevas_ventas["venta_alta_real_estimada"] = nuevas_ventas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)

In [37]:
nuevas_ventas[nuevas_ventas["venta_alta_real_estimada"] == nuevas_ventas["predicciones"]]

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,predicciones,prediccion_venta_alta,total_estimado,venta_alta_real_estimada
2,1003,2026-07-02,Oliver Adán,Incienso,Accesorios,1,450.0,Tarjeta,Temixco,450.0,0,Venta no alta,450.0,0
3,1004,2026-07-02,Mirna Cortés,Leche,Accesorios,1,400.0,Efectivo,Cuernavaca,400.0,0,Venta no alta,400.0,0
6,1007,2026-07-04,Marco Antonio Soliz,Mouse Pad,Accesorios,2,490.0,Efectivo,Jiutepec,980.0,0,Venta no alta,980.0,0
7,1008,2026-07-04,Jorge Humberto,TLOZ,Videojuegos,4,800.0,Tarjeta,Jiutepec,3200.0,1,Venta alta,3200.0,1

In [38]:
nuevas_ventas["coincide"] = nuevas_ventas["predicciones"] == nuevas_ventas["venta_alta_real_estimada"]

In [39]:
nuevas_ventas["coincide"].value_counts()

coincide
False    6
True     4
Name: count, dtype: int64

In [40]:
nuevas_ventas["predicciones"].value_counts()

predicciones
0    7
1    3
Name: count, dtype: int64

In [41]:
nuevas_ventas["distancia_a_1000"] = (nuevas_ventas["total_estimado"] - 1000).abs()
cerca_limite = nuevas_ventas[nuevas_ventas["distancia_a_1000"] <= 200]

In [42]:
cerca_limite

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,predicciones,prediccion_venta_alta,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
4,1005,2026-07-03,Valentina Eslava,Cable Ethernet,Accesorios,5,210.0,Efectivo,Jiutepec,1050.0,0,Venta no alta,1050.0,1,False,50.0
6,1007,2026-07-04,Marco Antonio Soliz,Mouse Pad,Accesorios,2,490.0,Efectivo,Jiutepec,980.0,0,Venta no alta,980.0,0,True,20.0

In [43]:
nuevas_ventas.to_csv("examen_predicciones.csv", index=False)

In [44]:
nuevas_ventas[nuevas_ventas["predicciones"] != nuevas_ventas["venta_alta_real_estimada"]]

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,predicciones,prediccion_venta_alta,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
0,1001,2026-07-01,Cesar Emilio,Mouse Pad,Accesorios,3,1000.0,Efectivo,Jiutepec,3000.0,0,Venta no alta,3000.0,1,False,2000.0
1,1002,2026-07-01,Fernando Antonio,Refrigerador,Accesorios,2,2000.0,Tarjeta,Jiutepec,4000.0,0,Venta no alta,4000.0,1,False,3000.0
4,1005,2026-07-03,Valentina Eslava,Cable Ethernet,Accesorios,5,210.0,Efectivo,Jiutepec,1050.0,0,Venta no alta,1050.0,1,False,50.0
5,1006,2026-07-03,Mateo Castañeda,Memoria RAM,Accesorios,2,2000.0,Tarjeta,Jiutepec,4000.0,0,Venta no alta,4000.0,1,False,3000.0
8,1009,2026-07-05,Valeria Fernanda,TBOI,Videojuegos,2,220.0,Efectivo,Jiutepec,440.0,1,Venta alta,440.0,0,False,560.0
9,1010,2026-07-05,Frida Rosas,Mewgenics,Videojuegos,2,160.0,Efectivo,Tultepec,320.0,1,Venta alta,320.0,0,False,680.0

Preguntas obligatorias:

Cuantas ventas nuevas evaluaste?
10

Cuantas fueron predichas como venta alta?
3

Cuantas fueron predichas como venta no alta?
7

Cuantas coincidieron con la regla manual?
4

Cuantas no coincidieron?
6

Que ventas no coincidieron?
Tres que eran muy por encima de 1000, dos que estaban bastante por debajo de 1000, y uno cercano a 1000

Los errores estuvieron cerca del limite de 1000?
1 de los 6

Que paso con la categoria nueva?
Se eliminó de las columnas

Que paso con la ciudad nueva?
Se eliminó de las columnas

## Resumen Para README

Completa esta seccion al final:

```text
Nombre: Cesar Emilio Contreras Cortés
Grupo: 9A
Materia: Extracción de conocimiento de base de datos
Exactitud obtenida: Original: 100
Ventas nuevas evaluadas: 10
Coincidencias: 2
Errores: 8
Conclusion breve: Inicialmente solo me salían 2 coincidencias en las predicciones pese a todos los pasos estar correctos. Finalmente intenté volver a cambiar las columnas nuevas, ya que casi todas las ciudades y categorías eran nuevas. Tras eso siguen coincidiendo solo 4. Esto me hace pensar en que aunque se pueda utilizar reindex() para poder ajustar las columnas a las que deberían ser, esto deja de lado el hecho de que si esa columna no existía se elimina, quedando en 0 en todas las demás. Esto puede hacer no solo que baje la predicción, sino incluso que voltee la predicción totalmente de la real, lo que es un problema muy grande. Por lo que es muy importante que al momento de entrenar el modelo se abarque una gran cantidad de datos, así evitando eliminar forzosamente las nuevas y variando la exactitud de la predicción
```