In [27]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
# Carga el dataset con pandas.
ventas = pd.read_csv("ventas_ecommerce_limpio.csv")

In [14]:
## ------------- Parte 2. Revision Del Dataset -------------
# Realiza lo siguiente:
#1. Muestra las primeras filas.
ventas.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,total_calculado,venta_alta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0,250.0,0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0,650.0,0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0,900.0,0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0,800.0,0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0,360.0,0

In [4]:
#2. Revisa las columnas.
ventas.columns

Index(['id_venta', 'fecha', 'cliente', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'metodo_pago', 'ciudad', 'total_venta'],
      dtype='object')

In [5]:
#3. Muestra cuantas filas y columnas tiene.
ventas.shape

(60, 10)

In [6]:
#4. Revisa si hay valores nulos.
ventas.isnull().sum()

id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64

In [8]:
#5. Verifica que exista la columna `total_venta`.
ventas["total_venta"].head()

0    250.0
1    650.0
2    900.0
3    800.0
4    360.0
Name: total_venta, dtype: float64

In [11]:
#6. Verifica que `total_venta` coincida con `cantidad * precio_unitario`.
ventas["total_calculado"] = ventas["cantidad"] * ventas["precio_unitario"]
ventas[ventas["total_venta"] != ventas["total_calculado"]]

Empty DataFrame
Columns: [id_venta, fecha, cliente, producto, categoria, cantidad, precio_unitario, metodo_pago, ciudad, total_venta, total_calculado]
Index: []

In [12]:
#7. Escribe una observacion breve sobre el estado del dataset.
# El dataset no tiene valores nulos y el total esta muy bien calculado, listo para poder ser procesado

In [15]:
## ------------- Parte 3. Variable Objetivo -------------

# Crea la columna:
ventas["venta_alta"] = ventas["total_venta"].apply(lambda x: 1 if x >= 1000 else 0)

In [16]:
# 2. Cuenta cuantas ventas quedaron como 1 y cuantas como 0.
ventas["venta_alta"].value_counts()

venta_alta
1    40
0    20
Name: count, dtype: int64

In [17]:
# Por que venta_alta es la variable objetivo?
# Porque es la que tiene los resultados que buscamos predecir.

In [18]:
## ------------- Parte 4. Variables De Entrada -------------
# Usa como variables de entrada:

# cantidad, precio_unitario, categoria, metodo_pago, ciudad

# Usa como variable objetivo:

# venta_alta

In [19]:
# Indicaciones:

# 1. Crea `X`.
X = ventas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [20]:
# 2. Crea `y`.
y = ventas["venta_alta"]

In [21]:
# 3. Convierte variables categoricas con `pd.get_dummies()`.
X = pd.get_dummies(X)

In [22]:
# 4. Guarda la lista de columnas generadas.
columnas_modelo = X.columns.tolist()

In [23]:
# 5. Muestra las primeras filas de `X` despues de `get_dummies()`.
X.head(5)

,cantidad,precio_unitario,categoria_Accesorios,categoria_Electronica,categoria_Muebles,metodo_pago_Efectivo,metodo_pago_Tarjeta,metodo_pago_Transferencia,ciudad_Cuernavaca,ciudad_Emiliano Zapata,ciudad_Jiutepec,ciudad_Temixco
0,1,250.0,True,False,False,True,False,False,True,False,False,False
1,1,650.0,True,False,False,False,True,False,False,False,True,False
2,1,900.0,True,False,False,False,True,False,False,False,False,True
3,1,800.0,True,False,False,True,False,False,True,False,False,False
4,2,180.0,True,False,False,True,False,False,False,False,True,False

In [24]:
# Por que no se debe usar total_venta como variable de entrada si venta_alta se creo a partir de total_venta?
# porque total_venta ya se asigno a venta_alta al principio, y ademas ya tiene la condicion

In [25]:
## ------------- Parte 5. Entrenamiento Y Evaluacion -------------
# Entrena un modelo con `DecisionTreeClassifier`.

# Indicaciones:

In [29]:
#1. Divide los datos en entrenamiento y prueba.
#2. Usa 80% entrenamiento y 20% prueba.
#3. Usa `random_state=42`.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [30]:
# 4. Entrena el modelo.
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [31]:
# 5. Genera predicciones con los datos de prueba.
predicciones = modelo.predict(X_test)

In [32]:
# 6. Calcula exactitud.
exactitud = accuracy_score(y_test, predicciones)
print("Exactitud:", exactitud)

Exactitud: 1.0

In [33]:
# 7. Muestra matriz de confusion.
matriz = confusion_matrix(y_test, predicciones)
print(matriz)

[[4 0]
 [0 8]]

In [35]:
# 8. Crea una tabla llamada `resultados_prueba` con:
resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": predicciones
})
resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

In [36]:
# 9. Cuenta cuantos aciertos y cuantos errores hubo.
resultados_prueba["coincide"].value_counts()

coincide
True    12
Name: count, dtype: int64

In [37]:
# Preguntas obligatorias:

# 1. Cual fue la exactitud?
# 1.0
# 2. Cuantos aciertos tuvo el modelo?
# 12
# 3. Cuantos errores tuvo el modelo?
# 0
# 4. Que indica la matriz de confusion?
# Que todos coinciden
# 5. Una buena exactitud significa que el modelo ya es perfecto? Explica.
# No, ya que pudo ser perfecto en la cantidad de datos que se tomo, pero si se hubuieran tomado mas seguramente si saldrian erroneos.

In [38]:
## ------------- Parte 6. Guardar Modelo Y Columnas -------------

In [41]:
# 1. Usa `joblib`.
# 2. Guarda el modelo entrenado.
# 3. Guarda la lista de columnas usadas durante el entrenamiento.
# 4. Verifica que los archivos aparezcan en tu carpeta.
joblib.dump(modelo, "modelo_examen_venta_alta.pkl")
joblib.dump(columnas_modelo, "columnas_examen_modelo.pkl")

['columnas_examen_modelo.pkl']

In [42]:
# Preguntas obligatorias:

# 1. Para que sirve guardar el modelo?
# Para reutilizar el modelo sin necesidad de volver a ejecutar todo.
# 2. Para que sirve guardar las columnas del entrenamiento?.
# Para ya tener datos entrenados y poder agregar mas.
# 3. Que problema puede aparecer si no guardas las columnas?
# Tendriamos que volver a hacer todo desde un incio.

In [43]:
## ------------- Parte 7. Ventas Nuevas -------------

In [46]:
# Crea un archivo llamado: examen_ventas_nuevas.csv
# Condiciones obligatorias:

# 1. Incluye al menos 4 ventas claramente altas.
# 2. Incluye al menos 4 ventas claramente no altas.
# 3. Incluye al menos 2 ventas cercanas al limite de 1000.
# 4. Incluye al menos 1 categoria nueva.
# 5. Incluye al menos 1 ciudad nueva.
# 6. No copies exactamente las ventas del pre examen.
# 7. No uses las mismas ventas que otro companero.
examen_ventas_nuevas = pd.DataFrame({
    "id_venta": [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],"fecha": ["2026-08-07", "2026-08-07", "2026-08-07", "2026-08-07", "2026-08-07",
    "2026-08-07", "2026-08-07", "2026-08-07", "2026-08-07", "2026-08-07"],
    "cliente": ["Adrian", "Uxue", "Elias", "Emanuel", "Cristian", "Amauri", "Fernandez", "Jose", "Juan", "Federico"],
    "producto": ["Tenis", "Laptop", "Teclado", "Audifonos", "WebCam", "Mouse", "Laptop", "Teclado", "Audifonos", "WebCam"],
    "categoria": ["Ropa", "Electronica", "Accesorios", "Electronica", "Accesorios", "Electronica", "Accesorios", "Electronica", "Accesorios", "Electronica"],
    "cantidad": [1, 1, 1, 1, 2, 1, 1, 1, 1, 2],
    "precio_unitario": [500, 12000, 998, 2500, 4500, 500, 12000, 999, 2500, 4500],
    "metodo_pago": ["Efectivo", "Tarjeta", "Efectivo", "Tarjeta", "Efectivo", "Tarjeta", "Efectivo", "Tarjeta", "Efectivo", "Tarjeta"],
    "ciudad": ["Cuernavaca", "Jiutepec", "Temixco", "Xochitepec", "Zapata", "Cuernavaca", "Jiutepec", "Temixco", "Xochitepec", "Zapata"],

})

examen_ventas_nuevas.to_csv("examen_ventas_nuevas.csv", index=False)

In [47]:
## ------------- Parte 8. Cargar Modelo Y Predecir -------------

In [48]:
# Usa el modelo guardado para predecir tus ventas nuevas.

# Indicaciones:

# 1. Carga `modelo_examen_venta_alta.pkl`.
modelo_cargado = joblib.load("modelo_examen_venta_alta.pkl")

In [49]:
# 2. Carga `columnas_examen_modelo.pkl`.
columnas_modelo = joblib.load("columnas_examen_modelo.pkl")

In [51]:
# 3. Carga `examen_ventas_nuevas.csv`.
nuevas = pd.read_csv("examen_ventas_nuevas.csv")

In [52]:
# 4. Selecciona las mismas variables de entrada usadas en entrenamiento.
# 5. Aplica `pd.get_dummies()`.
X_nuevas = nuevas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]
X_nuevas = pd.get_dummies(X_nuevas)

In [53]:
# 6. Alinea columnas con `reindex()`.
X_nuevas = X_nuevas.reindex(columns=columnas_modelo, fill_value=0)

In [56]:
# 7. Genera predicciones.
# 8. Agrega la columna: prediccion_venta_alta
# 9. Agrega la columna: interpretacion_prediccion
nuevas["prediccion_venta_alta"] = modelo_cargado.predict(X_nuevas)

nuevas["interpretacion_prediccion"] = nuevas["prediccion_venta_alta"].map({
    0: "Venta no alta",
    1: "Venta alta"
})

In [57]:
# 10. Guarda el resultado como:
nuevas.to_csv("examen_predicciones.csv", index=False)

In [58]:
# Que podria pasar si no usas reindex antes de predecir?
# Puede que no coincidan ya que no estan entrenadas aun

In [59]:
## ------------- Parte 9. Auditoria Del Modelo -------------

In [60]:
# Revisa si las predicciones coinciden con una regla manual.

# Indicaciones:

# 1. Calcula: total_estimado = cantidad * precio_unitario
nuevas["total_estimado"] = nuevas["cantidad"] * nuevas["precio_unitario"]

In [61]:
# 2. Crea: venta_alta_real_estimada
# usando:
# Si total_estimado >= 1000, entonces 1
# Si total_estimado < 1000, entonces 0
nuevas["venta_alta_real_estimada"] = nuevas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)

In [62]:
# 3. Compara: prediccion_venta_alta venta_alta_real_estimada
nuevas["coincide"] = nuevas["prediccion_venta_alta"] == nuevas["venta_alta_real_estimada"]

In [63]:
# 4. Crea la columna:coincide
nuevas["coincide"].value_counts()
# 5. Cuenta cuantas predicciones coincidieron y cuantas no.
# 6. Filtra las ventas que no coincidieron.
errores = nuevas[nuevas["coincide"] == False]

In [65]:
# 7. Revisa si los errores estan cerca del limite de 1000.
nuevas["distancia_a_1000"] = (nuevas["total_estimado"] - 1000).abs()

cerca_limite = nuevas[nuevas["distancia_a_1000"] <= 200]
cerca_limite

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
2,2003,2026-08-07,Elias,Teclado,Accesorios,1,998,Efectivo,Temixco,0,Venta no alta,998,0,True,2
7,2008,2026-08-07,Jose,Teclado,Electronica,1,999,Tarjeta,Temixco,1,Venta alta,999,0,False,1

In [66]:
nuevas.to_csv("examen_predicciones.csv", index=False)

In [69]:
nuevas.head(10)

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
0,2001,2026-08-07,Adrian,Tenis,Ropa,1,500,Efectivo,Cuernavaca,1,Venta alta,500,0,False,500
1,2002,2026-08-07,Uxue,Laptop,Electronica,1,12000,Tarjeta,Jiutepec,1,Venta alta,12000,1,True,11000
2,2003,2026-08-07,Elias,Teclado,Accesorios,1,998,Efectivo,Temixco,0,Venta no alta,998,0,True,2
3,2004,2026-08-07,Emanuel,Audifonos,Electronica,1,2500,Tarjeta,Xochitepec,1,Venta alta,2500,1,True,1500
4,2005,2026-08-07,Cristian,WebCam,Accesorios,2,4500,Efectivo,Zapata,0,Venta no alta,9000,1,False,8000
5,2006,2026-08-07,Amauri,Mouse,Electronica,1,500,Tarjeta,Cuernavaca,1,Venta alta,500,0,False,500
6,2007,2026-08-07,Fernandez,Laptop,Accesorios,1,12000,Efectivo,Jiutepec,0,Venta no alta,12000,1,False,11000
7,2008,2026-08-07,Jose,Teclado,Electronica,1,999,Tarjeta,Temixco,1,Venta alta,999,0,False,1
8,2009,2026-08-07,Juan,Audifonos,Accesorios,1,2500,Efectivo,Xochitepec,0,Venta no alta,2500,1,False,1500
9,2010,2026-08-07,Federico,WebCam,Electronica,2,4500,Tarjeta,Zapata,1,Venta alta,9000,1,True,8000

In [70]:
# Preguntas obligatorias:

# 1. Cuantas ventas nuevas evaluaste? 10
# 2. Cuantas fueron predichas como venta alta? 6
# 3. Cuantas fueron predichas como venta no alta? 4
# 4. Cuantas coincidieron con la regla manual? 4
# 5. Cuantas no coincidieron? 6
# 6. Que ventas no coincidieron? La de Adrian, Cristian, Amauri, Fernandez, Jose, Juan
# 7. Los errores estuvieron cerca del limite de 1000? Si
# 8. Que paso con la categoria nueva? Nada
# 9. Que paso con la ciudad nueva? Nada