In [ ]:

## Parte 1. Conceptos

Responde con tus palabras en esta seccion o en una celda Markdown de tu notebook.

1. Que es aprendizaje supervisado?
es cuando al modelo le cargas respuestas correctas para que valla aprendiendo el patron

2. Que es una variable objetivo?
es aquel dato el cual deseas predecir por ejemplo una venta alta o no alta

3. Que significa `venta_alta`?
es una variable objetivo la cual podemos desear predecir

4. Que diferencia hay entre `X` e `y`?
x  variables de entrada
y son las variables objetivo

5. Que es clasificacion?
es cuando separas los datos en categorias para poder predecir, podria ser (0 y 1)

6. Por que este problema es de clasificacion?
porque se intenta predecir si una venta es alta o no alta 

7. Que hace `DecisionTreeClassifier`?
es un modelo tipo arbol, va preguntando si/no hasta decidir.

8. Para que sirve separar entrenamiento y prueba?
para primero ir preparando al modelo para que aprenda de patrones y despues poder predecir 

9. Que significa exactitud?
cuando el modelo acierta a algo que se predijo 

10. Para que sirve una matriz de confusion?
detalle de en que se equivoco el
modelo

11. Que significa `fit()`?
se usa para entrenar el modelo

12. Que significa `predict()`?
genera predicciones 

13. Por que se usa `pd.get_dummies()`?
convierte texto en columnas numericas.
    
14. Por que se usa `reindex()` al predecir ventas nuevas?
porque acomoda columnas nuevas igual que las del entrenamiento.

15. Por que una prediccion no es una verdad absoluta?
el modelo puede fallar, sobre todo con pocos datos o casos nuevos

In [1]:

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = pd.read_csv("ventas_ecommerce_limpio.csv")

In [3]:
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

In [4]:
df.columns

Index(['id_venta', 'fecha', 'cliente', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'metodo_pago', 'ciudad', 'total_venta'],
      dtype='object')

In [5]:
df.shape

(60, 10)

In [6]:
df.isnull().sum()

id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64

In [ ]:
# 7. Escribe una observacion breve sobre el estado del dataset.
# existe una columna que no coincide ya que en precio_unitario esta en 180 y en total_venta esta en 360

In [7]:
df["venta_alta"] = df["total_venta"].apply(lambda x: 1 if x >= 1000 else 0)

In [ ]:
# Por que venta_alta es la variable objetivo?
# porque se intenta predecir si la venta fue alta o no alta

In [8]:
df["total_calculado"] = df["cantidad"] * df["precio_unitario"]

In [9]:
df[df["total_venta"] != df["total_calculado"]]

Empty DataFrame
Columns: [id_venta, fecha, cliente, producto, categoria, cantidad, precio_unitario, metodo_pago, ciudad, total_venta, venta_alta, total_calculado]
Index: []

In [10]:
df["venta_alta"].value_counts()

venta_alta
1    40
0    20
Name: count, dtype: int64

In [11]:
X = df[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]
y = df["venta_alta"]

In [12]:
X = pd.get_dummies(X)

In [13]:
columnas_modelo = X.columns.tolist()

In [ ]:
# Por que no se debe usar total_venta como variable de entrada si venta_alta se creo a partir de total_venta?
# porque la variable que se intenta predecir es venta_alta en este caso es la variable objetivo

In [14]:
X = pd.get_dummies(X)

In [15]:
columnas_modelo = X.columns.tolist()

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [17]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [19]:
predicciones = modelo.predict(X_test)

In [20]:
exactitud = accuracy_score(y_test, predicciones)
print("Exactitud:", exactitud)

Exactitud: 1.0

In [21]:
matriz = confusion_matrix(y_test, predicciones)
print(matriz)

[[4 0]
 [0 8]]

In [ ]:
# 1. Cual fue la exactitud?
# 1.0 de exactitud
# 2. Cuantos aciertos tuvo el modelo?
# 12 aciertos en total 
# 3. Cuantos errores tuvo el modelo?
# 0 errores 
# 4. Que indica la matriz de confusion?
# muestra el resultado de las predicciones clasificó correctamente 4 
# de la clase negativa 0 y 8 de la clase positiva 1
# 5. Una buena exactitud significa que el modelo ya es perfecto? Explica.
# No Una exactitud del 100% en un conjunto de prueba pequeño

In [22]:
resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": predicciones
})

In [23]:
resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

In [24]:
resultados_prueba["coincide"].value_counts()

coincide
True    12
Name: count, dtype: int64

In [25]:
aciertos = resultados_prueba[resultados_prueba["coincide"] == True]
errores = resultados_prueba[resultados_prueba["coincide"] == False]

In [27]:
len(aciertos)
len(errores)

0

In [28]:
joblib.dump(modelo, "modelo_examen_venta_alta.pkl")

['modelo_examen_venta_alta.pkl']

In [29]:
joblib.dump(columnas_modelo, "columnas_examen_modelo.pkl")

['columnas_examen_modelo.pkl']

In [ ]:
1. Para que sirve guardar el modelo?
para tener prueba del modelo y usarlo para otra prediccion 
2. Para que sirve guardar las columnas del entrenamiento?
para que asi el modelo tenga los datos de entrenamiento 
3. Que problema puede aparecer si no guardas las columnas?
el problema es que si no se encuentra la columna que se intenta predecir no tendra datos el modelo

In [34]:
nuevas = pd.DataFrame({
    "id_venta": [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
    "fecha": [
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
        "2026-08-07",
    ],
    "cliente": [
        "Cliente A",
        "Cliente B",
        "Cliente C",
        "Cliente D",
        "Cliente E",
        "Cliente F",
        "Cliente G",
        "Cliente H",
        "Cliente I",
        "Cliente J",
    ],
    "producto": [
        "Mouse",
        "Laptop",
        "Monitor",
        "PC",
        "Silla",
        "Escritorio",
        "Mueble",
        "Sofa",
        "Closet",
        "Memoria",
    ],
    "categoria": [
        "Accesorios",
        "Electronica",
        "Electronica",
        "Electronica",
        "Accesorios",
        "Electrodomesicos",
        "Electrodomesicos",
        "Electrodomesicos",
        "Electrodomesicos",
        "Electronica",
    ],
    "cantidad": [1, 1, 2, 1, 2, 1, 1, 3, 1, 3],
    "precio_unitario": [
        500,
        12000,
        700,
        500,
        600,
        12000,
        700,
        12000,
        400,
        12000,
    ],
    "metodo_pago": [
        "Efectivo",
        "Tarjeta",
        "Efectivo",
        "Tarjeta",
        "Efectivo",
        "Tarjeta",
        "Efectivo",
        "Tarjeta",
        "Efectivo",
        "Tarjeta",
    ],
    "ciudad": [
        "Cuernavaca",
        "Jiutepec, Nopalera",
        "Tetecalita,Cuernavaca",
        "Jiutepec,Amatitlan",
        "Chiconcuac,Cuernavaca",
        "Jiutepec",
        "Cuernavaca",
        "Jiutepec",
        "Cuernavaca",
        "Jiutepec",
    ], 
})

nuevas.to_csv("examen_ventas_nuevas.csv", index=False)

In [35]:
modelo_cargado = joblib.load("modelo_examen_venta_alta.pkl")

In [36]:
columnas_modelo = joblib.load("columnas_examen_modelo.pkl")

In [37]:
nuevas = pd.read_csv("examen_ventas_nuevas.csv")

In [38]:

X_nuevas = nuevas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]
X_nuevas = pd.get_dummies(X_nuevas)

In [39]:

X_nuevas = X_nuevas.reindex(columns=columnas_modelo, fill_value=0)

In [40]:
nuevas["prediccion_venta_alta"] = modelo_cargado.predict(X_nuevas)

In [41]:
nuevas["interpretacion_prediccion"] = nuevas["prediccion_venta_alta"].map({
    0: "Venta no alta",
    1: "Venta alta"
})

In [ ]:
# Que podria pasar si no usas reindex antes de predecir?
# que las columnas nuevas no quedaran alineadas con las columnas del entrenamiento

In [43]:
nuevas["total_estimado"] = nuevas["cantidad"] * nuevas["precio_unitario"]

In [44]:
nuevas["venta_alta_real_estimada"] = nuevas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)

In [45]:
nuevas["coincide"] = nuevas["prediccion_venta_alta"] == nuevas["venta_alta_real_estimada"]

In [46]:
nuevas["coincide"].value_counts()

coincide
True     6
False    4
Name: count, dtype: int64

In [47]:
errores = nuevas[nuevas["coincide"] == False]

In [51]:
nuevas["distancia_a_1000"] = (nuevas["total_estimado"] - 1000).abs()

In [54]:

cerca_limite = nuevas[nuevas["distancia_a_1000"] <= 200]
print(cerca_limite)

   id_venta       fecha    cliente producto   categoria  cantidad  \
4      2005  2026-08-07  Cliente E    Silla  Accesorios         2

   precio_unitario metodo_pago                 ciudad  prediccion_venta_alta  \
4              600    Efectivo  Chiconcuac,Cuernavaca                      0

  interpretacion_prediccion  total_estimado  venta_alta_real_estimada  \
4             Venta no alta            1200                         1

   coincide  distancia_a_1000
4     False               200

In [50]:
nuevas.to_csv("examen_predicciones.csv", index=False)

In [ ]:

1. Cuantas ventas nuevas evaluaste?
10 ventas nuevas

2. Cuantas fueron predichas como venta alta?
6 fueron predichas como venta alta

3. Cuantas fueron predichas como venta no alta?
4 fueron predichas como venta no alta

4. Cuantas coincidieron con la regla manual?
solo las que tienen la misma categoria que existia antes 

5. Cuantas no coincidieron?
4 no coincidieron

6. Que ventas no coincidieron?
los clientes con los id 2004, 2005, 2007, 2009

7. Los errores estuvieron cerca del limite de 1000?
Si los errores estan en ese rango

8. Que paso con la categoria nueva?
Al aplicar pd.get_dummies() y luego .reindex cualquier categoria nueva que no existia en el entrenamiento Electrodomesicos
fue ignorada sus columnas tomaron valor 0, por lo que el modelo no pudo usar esa informacion

9. Que paso con la ciudad nueva?
los nombres de ciudades nuevas o combinadas Jiutepec, Nopalera Tetecalita,Cuernavaca etc
no existian en las columnas del modelo original, asi que al hacer el reindex se rellenaron con 0