In [1]:
# ## Parte 1. Conceptos

# Responde con tus palabras en esta seccion o en una celda Markdown de tu notebook.

# 1. Que es aprendizaje supervisado?
# 2. Que es una variable objetivo?
# 3. Que significa `venta_alta`?
# 4. Que diferencia hay entre `X` e `y`?
# 5. Que es clasificacion?
# 6. Por que este problema es de clasificacion?
# 7. Que hace `DecisionTreeClassifier`?
# 8. Para que sirve separar entrenamiento y prueba?
# 9. Que significa exactitud?
# 10. Para que sirve una matriz de confusion?
# 11. Que significa `fit()`?
# 12. Que significa `predict()`?
# 13. Por que se usa `pd.get_dummies()`?
# 14. Por que se usa `reindex()` al predecir ventas nuevas?
# 15. Por que una prediccion no es una verdad absoluta?

# ### Respuestas Del Estudiante

# Escribe aqui tus respuestas:

# 1. Es un modelo que intenta realizar predicciones a partir de un conjunto de datos ya completos
# 2. La variable objetivo (y) es el valor que se intenta interpretar
# 3. Es la variable objetivo, es decir, la columna a la cual se va a interpretar según las predicciones
# 4. La "X" significa los valores de entrada mientras que la "Y" es la variable objetivo
# 5. Es la acción de clasificar algo mediante categorías o clases
# 6. Porque queremos saber a que tipo de venta pertenece cada una, ya sea venta alta o venta no alta
# 7. Crea un entrenamiento para el modelo
# 8. Para que el modelo sepa cuales serán los patrones en el entrenamiento y el resto sea de prueba, donde se intente predecir 
# 9. Significa la precisión que hay entre los registros del dataset
# 10. Sirve para mostrar los datos que pueden ser clasificados como negativos o fals
# 11. Es el que va a entrenar el modelo
# 12. Es el que va a predecir los datos del modelo con (X_test)
# 13. Sirve para que las columnas nuevas tengan el mismo orden y estructura 
# 14. Porque alinea las columnas nuevas con las columnas del entrenamiento
# 15. Porque puede haber un margen de error y no siempre es correcto

In [2]:
## Parte 2. Revision Del Dataset
# Carga el dataset con pandas.
import pandas as pd
df = pd.read_csv("ventas_ecommerce_limpio.csv")
# Realiza lo siguiente:

In [3]:
# 1. Muestra las primeras filas.
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

In [4]:
# 2. Revisa las columnas.
df.columns

Index(['id_venta', 'fecha', 'cliente', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'metodo_pago', 'ciudad', 'total_venta'],
      dtype='object')

In [5]:
# 3. Muestra cuantas filas y columnas tiene.
df.shape

(60, 10)

In [6]:
# 4. Revisa si hay valores nulos.
df.isnull().sum()

id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64

In [10]:
# 5. Verifica que exista la columna `total_venta`.
if "total_venta" in df.columns:
    print("Existe la columna 'total_venta'")
else:
    print("No existe la columna 'total_venta")

Existe la columna 'total_venta'

In [11]:
# 6. Verifica que `total_venta` coincida con `cantidad * precio_unitario`.
df["total_calculado"] = df["cantidad"] * df["precio_unitario"]

In [12]:
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,total_calculado
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0,360.0

In [13]:
# 7. Escribe una observacion breve sobre el estado del dataset.
# El dataset no contiene valores nulos, además la columna "total_venta" existe y su cálculo es correcto

In [14]:
# ## Parte 3. Variable Objetivo

# Crea la columna: venta_alta
# Regla:
# Si total_venta >= 1000, venta_alta = 1
# Si total_venta < 1000, venta_alta = 0

# Indicaciones:

# 1. Puedes usar una funcion normal o una lambda.
df["venta_alta"] = df["total_venta"].apply(lambda x: 1 if x >= 1000 else 0)
# 2. Cuenta cuantas ventas quedaron como 1 y cuantas como 0.
df["venta_alta"].value_counts()

venta_alta
1    40
0    20
Name: count, dtype: int64

In [15]:
# Pregunta obligatoria:
# Por que venta_alta es la variable objetivo? Porque es la que nos esta ayudando a interpretar la predicción: si una venta es alta o no

In [16]:
# ## Parte 4. Variables De Entrada

# Usa como variables de entrada: cantidad, precio_unitario, categoria, metodo_pago, ciudad
# Usa como variable objetivo: venta_alta

# Indicaciones:
# 1. Crea `X`.
X = df[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [17]:
# 2. Crea `y`.
y = df["venta_alta"]

In [18]:
# 3. Convierte variables categoricas con `pd.get_dummies()`.
X = pd.get_dummies(X)

In [19]:
# 4. Guarda la lista de columnas generadas.
columnas_modelo = X.columns.tolist()

In [20]:
# 5. Muestra las primeras filas de `X` despues de `get_dummies()`.
X.head()

,cantidad,precio_unitario,categoria_Accesorios,categoria_Electronica,categoria_Muebles,metodo_pago_Efectivo,metodo_pago_Tarjeta,metodo_pago_Transferencia,ciudad_Cuernavaca,ciudad_Emiliano Zapata,ciudad_Jiutepec,ciudad_Temixco
0,1,250.0,True,False,False,True,False,False,True,False,False,False
1,1,650.0,True,False,False,False,True,False,False,False,True,False
2,1,900.0,True,False,False,False,True,False,False,False,False,True
3,1,800.0,True,False,False,True,False,False,True,False,False,False
4,2,180.0,True,False,False,True,False,False,False,False,True,False

In [21]:
# Pregunta obligatoria:
# Por que no se debe usar total_venta como variable de entrada si venta_alta se creo a partir de total_venta? Porque podría haber un error en la
# interpretación

In [22]:
# ## Parte 5. Entrenamiento Y Evaluacion

# Entrena un modelo con `DecisionTreeClassifier`.
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Indicaciones:
# 1. Divide los datos en entrenamiento y prueba.
# 2. Usa 80% entrenamiento y 20% prueba.
# 3. Usa `random_state=42`.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
# 4. Entrena el modelo.
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [24]:
# 5. Genera predicciones con los datos de prueba.
predicciones = modelo.predict(X_test)

In [25]:
# 6. Calcula exactitud.
exactitud = accuracy_score(y_test, predicciones)
print("Exactitud:", exactitud)

Exactitud: 1.0

In [26]:
# 7. Muestra matriz de confusion.
matriz = confusion_matrix(y_test, predicciones)
print(matriz)

[[4 0]
 [0 8]]

In [27]:
# 8. Crea una tabla llamada `resultados_prueba` con: valor_real, prediccion, coincide
resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": predicciones
})
resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

In [28]:
# 9. Cuenta cuantos aciertos y cuantos errores hubo.
resultados_prueba["coincide"].value_counts()

aciertos = resultados_prueba[resultados_prueba["coincide"] == True]
errores = resultados_prueba[resultados_prueba["coincide"] == False]

In [31]:
print(resultados_prueba)

    valor_real  prediccion  coincide
0            0           0      True
5            0           0      True
36           1           1      True
45           1           1      True
13           0           0      True
54           1           1      True
33           1           1      True
48           1           1      True
12           0           0      True
57           1           1      True
46           1           1      True
50           1           1      True

In [29]:
len(aciertos)

12

In [30]:
len(errores)

0

In [32]:
# Preguntas obligatorias:
# 1. Cual fue la exactitud? La exactitud fue de 1.0
# 2. Cuantos aciertos tuvo el modelo? Tuvo 12 aciertos
# 3. Cuantos errores tuvo el modelo? Tuvo 0 errores
# 4. Que indica la matriz de confusion? 4 ventas clasificadas correctamente como ventas altas, 0 ventas altas clasificadas como no ventas altas, 0 ventas
# no altas clasificadas correctamente como ventas no altas, 8 ventas no altas clasificadas como no ventas no altas
# 5. Una buena exactitud significa que el modelo ya es perfecto? Explica.
# No, porque siempre existe la posibilidad de que haya margenes de errores o un mal cálculo

In [33]:
# ## Parte 6. Guardar Modelo Y Columnas

# Guarda: modelo_examen_venta_alta.pkl, columnas_examen_modelo.pkl
# Indicaciones:
# 1. Usa `joblib`.
import joblib
# 2. Guarda el modelo entrenado.
joblib.dump(modelo, "modelo_examen_venta_alta.pkl")

['modelo_examen_venta_alta.pkl']

In [34]:
# 3. Guarda la lista de columnas usadas durante el entrenamiento.
joblib.dump(columnas_modelo, "columnas_examen_modelo.pkl")

['columnas_examen_modelo.pkl']

In [35]:
# 4. Verifica que los archivos aparezcan en tu carpeta.
# Si existen

In [36]:
# Preguntas obligatorias:
# 1. Para que sirve guardar el modelo? Para que al momento de producción sea más fácil cargarlo ya con toda la estructura
# 2. Para que sirve guardar las columnas del entrenamiento? Para que las olumnas guarden el mismo orden y la misma estructura
# 3. Que problema puede aparecer si no guardas las columnas? Que no creen los valores en las columnas correspondientes

In [37]:
# ## Parte 7. Ventas Nuevas

# Crea un archivo llamado: examen_ventas_nuevas.csv
# Debe contener al menos 10 ventas nuevas.

# Columnas obligatorias:
# id_venta
# fecha
# cliente
# producto
# categoria
# cantidad
# precio_unitario
# metodo_pago
# ciudad

# Condiciones obligatorias:
# 1. Incluye al menos 4 ventas claramente altas.
# 2. Incluye al menos 4 ventas claramente no altas.
# 3. Incluye al menos 2 ventas cercanas al limite de 1000.
# 4. Incluye al menos 1 categoria nueva.
# 5. Incluye al menos 1 ciudad nueva.
# 6. No copies exactamente las ventas del pre examen.
# 7. No uses las mismas ventas que otro companero.

nuevas = pd.DataFrame({
    "id_venta": [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
    "fecha": ["2026-08-07", "2026-08-07", "2026-08-08", "2026-08-09", "2026-08-09", "2026-08-10", "2026-08-10", "2026-08-11", "2026-08-12", "2026-08-13",],
    "cliente": ["Cliente A", "Cliente B", "Cliente C", "Cliente D", "Cliente E", "Cliente F","Cliente G","Cliente H","Cliente I", "Cliente J"],
    "producto": ["Mouse", "Laptop", "Cuaderno", "Aretes", "Teclado", "Laptop", "Mouse", "TV", "Tablet", "Plumones"],
    "categoria": ["Accesorios", "Electronica", "Papelería", "Joyería", "Accesorios", "Electronica", "Accesorios", "Electronica", "Electronica", "Papelería"],
    "cantidad": [4, 1, 2, 3, 2, 4, 2, 4, 1, 3],
    "precio_unitario": [500, 12000, 45, 150, 550, 230, 450, 2000, 650, 150],
    "metodo_pago": ["Efectivo", "Tarjeta", "Efectivo", "Tarjeta", "Efectivo", "Tarjeta", "Efectivo", "Tarjeta", "Efectivo", "Tarjeta"],
    "ciudad": ["Cuernavaca", "Jiutepec", "Cuernavaca", "Jiutepec", "Temixco", "Emiliano Zapata", "Jojutla", "Temixco", "Cuernavaca", "Temixco",]
})

nuevas.to_csv("examen_ventas_nuevas.csv", index=False)

In [38]:
# ## Parte 8. Cargar Modelo Y Predecir

# Usa el modelo guardado para predecir tus ventas nuevas.
# Indicaciones:
# 1. Carga `modelo_examen_venta_alta.pkl`.
modelo_cargado = joblib.load("modelo_examen_venta_alta.pkl")

In [39]:
# 2. Carga `columnas_examen_modelo.pkl`.
columnas_modelo = joblib.load("columnas_examen_modelo.pkl")

In [40]:
# 3. Carga `examen_ventas_nuevas.csv`.
nuevas = pd.read_csv("examen_ventas_nuevas.csv")

In [41]:
# 4. Selecciona las mismas variables de entrada usadas en entrenamiento.
X_nuevas = nuevas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [42]:
# 5. Aplica `pd.get_dummies()`.
X_nuevas = pd.get_dummies(X_nuevas)

In [43]:
# 6. Alinea columnas con `reindex()`.
X_nuevas = X_nuevas.reindex(columns=columnas_modelo, fill_value=0)

In [44]:
# 7. Genera predicciones.
nuevas["prediccion_venta_alta"] = modelo_cargado.predict(X_nuevas)

In [45]:
# 8. Agrega la columna: prediccion_venta_alta
# 9. Agrega la columna: interpretacion_prediccion
#     donde:
#         0 = Venta no alta
#         1 = Venta alta
nuevas["interpretacion_prediccion"] = nuevas["prediccion_venta_alta"].map({
    0: "Venta no alta",
    1: "Venta alta"
})

In [46]:
# 10. Guarda el resultado como: examen_predicciones.csv
nuevas.to_csv("examen_predicciones.csv", index=False)

In [47]:
# Pregunta obligatoria:
# Que podria pasar si no usas reindex antes de predecir? Las olumnas no estarán alineadas

In [48]:
# ## Parte 9. Auditoria Del Modelo

# Revisa si las predicciones coinciden con una regla manual.
# Indicaciones:
# 1. Calcula: total_estimado = cantidad * precio_unitario
nuevas["total_estimado"] = nuevas["cantidad"] * nuevas["precio_unitario"]

In [49]:
# 2. Crea: venta_alta_real_estimada
# usando:
# Si total_estimado >= 1000, entonces 1
# Si total_estimado < 1000, entonces 0
nuevas["venta_alta_real_estimada"] = nuevas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)

In [50]:
# 3. Compara: prediccion_venta_alta y venta_alta_real_estimada
# 4. Crea la columna: coincide
nuevas["coincide"] = nuevas["prediccion_venta_alta"] == nuevas["venta_alta_real_estimada"]

In [51]:
# 5. Cuenta cuantas predicciones coincidieron y cuantas no.
nuevas["coincide"].value_counts()

coincide
False    7
True     3
Name: count, dtype: int64

In [53]:
# 6. Filtra las ventas que no coincidieron.
errores = nuevas[nuevas["coincide"] == False]
print(errores)

   id_venta       fecha    cliente  producto    categoria  cantidad  \
0      2001  2026-08-07  Cliente A     Mouse   Accesorios         4
2      2003  2026-08-08  Cliente C  Cuaderno    Papelería         2
3      2004  2026-08-09  Cliente D    Aretes      Joyería         3
4      2005  2026-08-09  Cliente E   Teclado   Accesorios         2
5      2006  2026-08-10  Cliente F    Laptop  Electronica         4
8      2009  2026-08-12  Cliente I    Tablet  Electronica         1
9      2010  2026-08-13  Cliente J  Plumones    Papelería         3

   precio_unitario metodo_pago           ciudad  prediccion_venta_alta  \
0              500    Efectivo       Cuernavaca                      0
2               45    Efectivo       Cuernavaca                      1
3              150     Tarjeta         Jiutepec                      1
4              550    Efectivo          Temixco                      0
5              230     Tarjeta  Emiliano Zapata                      1
8              650    Efectivo       Cuernavaca                      1
9              150     Tarjeta          Temixco                      1

  interpretacion_prediccion  total_estimado  venta_alta_real_estimada  \
0             Venta no alta            2000                         1
2                Venta alta              90                         0
3                Venta alta             450                         0
4             Venta no alta            1100                         1
5                Venta alta             920                         0
8                Venta alta             650                         0
9                Venta alta             450                         0

   coincide
0     False
2     False
3     False
4     False
5     False
8     False
9     False

In [54]:
# 7. Revisa si los errores estan cerca del limite de 1000.
nuevas["distancia_a_1000"] = (nuevas["total_estimado"] - 1000).abs()
cerca_limite = nuevas[nuevas["distancia_a_1000"] <= 200]

In [55]:
cerca_limite

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
4,2005,2026-08-09,Cliente E,Teclado,Accesorios,2,550,Efectivo,Temixco,0,Venta no alta,1100,1,False,100
5,2006,2026-08-10,Cliente F,Laptop,Electronica,4,230,Tarjeta,Emiliano Zapata,1,Venta alta,920,0,False,80
6,2007,2026-08-10,Cliente G,Mouse,Accesorios,2,450,Efectivo,Jojutla,0,Venta no alta,900,0,True,100

In [56]:
# 8. Guarda de nuevo `examen_predicciones.csv` con las columnas de auditoria.
nuevas.to_csv("examen_predicciones.csv", index=False)

In [57]:
# Preguntas obligatorias:
# 1. Cuantas ventas nuevas evaluaste? 10 ventas fueron evaluadas
# 2. Cuantas fueron predichas como venta alta? Fueron 4
# 3. Cuantas fueron predichas como venta no alta? Fueron 6
# 4. Cuantas coincidieron con la regla manual? 3
# 5. Cuantas no coincidieron? 7
# 6. Que ventas no coincidieron? La ventas con id: 2001, 2003, 2004, 2005, 2006, 2008, 2009, 2010
# 7. Los errores estuvieron cerca del limite de 1000? Si
# 8. Que paso con la categoria nueva? Se agrego al dataset
# 9. Que paso con la ciudad nueva? Se agrego al dataset