In [14]:
## Parte 1. Conceptos

#Responde con tus palabras en esta seccion o en una celda Markdown de tu notebook.

#1. Que es aprendizaje supervisado?
#2. Que es una variable objetivo?
#3. Que significa `venta_alta`?
#4. Que diferencia hay entre `X` e `y`?
#5. Que es clasificacion?
#6. Por que este problema es de clasificacion?
#7. Que hace `DecisionTreeClassifier`?
#8. Para que sirve separar entrenamiento y prueba?
#9. Que significa exactitud?
#10. Para que sirve una matriz de confusion?
#11. Que significa `fit()`?
#12. Que significa `predict()`?
#13. Por que se usa `pd.get_dummies()`?
#14. Por que se usa `reindex()` al predecir ventas nuevas?
#15. Por que una prediccion no es una verdad absoluta?

### Respuestas Del Estudiante

#Escribe aqui tus respuestas:

#1.Es donde entrenamos a un modelo utilizando datos que ya tienes las respuestas 
#correctas para que pueda aprendenr y asi predecir los resultados de datos nuevos
#2.Es la columna donde se especifica el dataset el cual el modelo intentara predecir tambien llamada y
#3.La venta alta es nuestra variable objetivo que se creo par aindicar con un 1 si la venta fue mas de 1000 y con un 0 si fue menor
#4.La x representa las variables de entrada que usa el modelo para aprender mientras que la y es la respuesta o tambien llamada la variable objetivo
#que se quiere predecir
#5.Es un problema de aprendizaje en donde el objetivo tiene que predecir una categoria como si fuera alto o bajo como en este caso venta alta 
#o venta baja en lugar de ser un valor numerico
#6.Por que en este caso intentamos predecir si la venta es de la categoria lata o no alta 
#7.El decissionTreeClassifier es un algoritmo basado en reglas de decision basado en las caracteristicas de los datos y se ramifica como si fuera una arbol
#8.Para el que modelo aprenda con una parte de datos es decir con una parte de los datos entrene y con el otro podamos medir el rendimiento real de los 
#datos es decir datos que jamas a visto asi evitamos que memorice
#9.Es una metrica que nos infica el procentaje de predicciones que fue correcta y que modelo hizo el total de predicciones
#10.Es una tabla que nos permite ver el desempeño que tuvo cada modelo desglosado por aciertos y errores de cada clase 
#11.Se le llama al metodo de un codigo que ejecuta un proceso de entrenamiento y se ajusta al modelo de datos que le demos
#12.Se le llama al metodo que ya esta entrenado y este genera predicciones sobre un nuevo conjunto de datos de entrada
#13.Lo que hace el get_dummies es que convierte de texto a numeros para que el modelo lo pueda interpretar de mejor manera
#14.Para que los datos nuevos tengan la misma cantidad y orden de columnas que los datos con el modelo que fue entrenado
#15.Una prediccion nunca se tiene que tomar como verdad absoluta ya que existe un margen de error y puede que sea incorrecta

In [15]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("ventas_ecommerce_limpio.csv")

display(df.head())
print(df.columns)
print(df.shape)
print(df.isnull().sum())

# Verificar total_venta coincida con cantidad * precio_unitario
df["total_calculado"] = df["cantidad"] * df["precio_unitario"]
inconsistencias = df[df["total_venta"] != df["total_calculado"]]

print(f"Se encontraron {len(inconsistencias)} registros inconsistentes.")

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

Index(['id_venta', 'fecha', 'cliente', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'metodo_pago', 'ciudad', 'total_venta'],
      dtype='object')
(60, 10)
id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64
Se encontraron 0 registros inconsistentes.

In [16]:
#Observacion del data set
#El data set fue cargado correctamente y la estructura valores nuelo esta bien ademas se comprobo si existia discrepancia entre las columnas totalventa
#y el calculo de cantidad por precio unitario resumen TODO BIEN

In [18]:
## Parte 3. Variable Objetivo
df["venta_alta"] = df["total_venta"].apply(lambda x: 1 if x >= 1000 else 0)
print(df["venta_alta"].value_counts())

#Por que venta_alta es la variable objetivo?
#Por que el objetivo es desarrollar un modelo supervisado de clasificacion para que aprenda si la venta es alta o no

venta_alta
1    40
0    20
Name: count, dtype: int64

In [19]:
## Parte 4. Variables De Entrada
X = df[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]
y = df["venta_alta"]

# Convertir variables categoricas
X = pd.get_dummies(X)
columnas_modelo = X.columns.tolist()

display(X.head())

,cantidad,precio_unitario,categoria_Accesorios,categoria_Electronica,categoria_Muebles,metodo_pago_Efectivo,metodo_pago_Tarjeta,metodo_pago_Transferencia,ciudad_Cuernavaca,ciudad_Emiliano Zapata,ciudad_Jiutepec,ciudad_Temixco
0,1,250.0,True,False,False,True,False,False,True,False,False,False
1,1,650.0,True,False,False,False,True,False,False,False,True,False
2,1,900.0,True,False,False,False,True,False,False,False,False,True
3,1,800.0,True,False,False,True,False,False,True,False,False,False
4,2,180.0,True,False,False,True,False,False,False,False,True,False

In [ ]:
#¿Por qué no se debe usar total_venta como variable de entrada si venta_alta se creó a partir de total_venta?
#Por que al hacer eso se estaria haciendo una fuga de datos y ke estariamos dando al modelo la respuesta directamente en la variable
#de entrada lo que haria que el modelo no funcione en predecir los datos que aun no conoce

In [20]:
# Parte 5. Entrenamiento Y Evaluacion
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Entrenar modelo
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

# Predecir y evaluar
predicciones = modelo.predict(X_test)
exactitud = accuracy_score(y_test, predicciones)
matriz = confusion_matrix(y_test, predicciones)

print(f"Exactitud: {exactitud}")
print("Matriz de confusion:")
print(matriz)

# Tabla de resultados
resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": predicciones
})
resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

aciertos = len(resultados_prueba[resultados_prueba["coincide"] == True])
errores = len(resultados_prueba[resultados_prueba["coincide"] == False])

print(f"\nAciertos: {aciertos}")
print(f"Errores: {errores}")

Exactitud: 1.0
Matriz de confusion:
[[4 0]
 [0 8]]

Aciertos: 12
Errores: 0

In [ ]:
#1. ¿Cuál fue la exactitud? 1.0
#2. ¿Cuántos aciertos tuvo el modelo? 12
#3. ¿Cuántos errores tuvo el modelo? 0
#4. ¿Qué indica la matriz de confusión? Nos enseña la distribucion de predicciones cuantos ceros verdaderos predijimos como ceros y cuantos unos
#como unos y donde se equivoco
#5. ¿Una buena exactitud significa que el modelo ya es perfecto?
#No una exactitud perfecta en problemas simples indica un sobreajuste ademas el modelo puede fallar en la vida real si se intruducen varibles como 
#nuevas ciudades o categorias que el modelo no a aprendido

In [21]:
# Parte 6. Guardar Modelo Y Columnas
joblib.dump(modelo, "modelo_examen_venta_alta.pkl")
joblib.dump(columnas_modelo, "columnas_examen_modelo.pkl")

['columnas_examen_modelo.pkl']

In [22]:
# Parte 7. Ventas Nuevas
ventas_nuevas = pd.DataFrame({
    "id_venta": [3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010],
    "fecha": ["2026-08-07"] * 10,
    "cliente": [f"Cliente {chr(65+i)}" for i in range(10)],
    "producto": ["Monitor", "Teclado", "Laptop", "Cable HDMI", "Mouse", "Escritorio", "Silla", "Hub USB", "Impresora 3D", "Webcam"],
    "categoria": ["Electronica", "Accesorios", "Electronica", "Accesorios", "Accesorios", "Muebles", "Muebles", "Accesorios", "NuevaCategoriaDIY", "Accesorios"],
    "cantidad": [2, 1, 1, 3, 1, 1, 1, 2, 1, 2],
    "precio_unitario": [2500, 300, 15000, 100, 150, 450, 550, 490, 8000, 600], 
    "metodo_pago": ["Tarjeta", "Efectivo", "Transferencia", "Efectivo", "Efectivo", "Tarjeta", "Tarjeta", "Efectivo", "Transferencia", "Tarjeta"],
    "ciudad": ["CDMX", "Puebla", "Guadalajara", "Monterrey", "Merida", "Tijuana", "Leon", "Puebla", "NuevaCiudadTech", "CDMX"] 
})

# Notas de las condiciones cumplidas:
# Ventas claramente altas: Monitor(5000), Laptop(15000), Impresora 3D(8000), Webcam(1200) = 4 altas
# Ventas claramente bajas: Teclado(300), Cable HDMI(300), Mouse(150), Silla(550) = 4 bajas
# Ventas cerca de 1000: Escritorio(450*1=450 - Ojo, ajustemos una a 980), Hub USB(490*2=980) 
# Vamos a ajustar el escritorio para que quede en 1050 

ventas_nuevas.loc[5, "precio_unitario"] = 1050

ventas_nuevas.to_csv("examen_ventas_nuevas.csv", index=False)
print("Ventas nuevas creadas y guardadas en CSV")

Ventas nuevas creadas y guardadas en CSV.

In [23]:
# Parte 8. Cargar Modelo Y Predecir
modelo_cargado = joblib.load("modelo_examen_venta_alta.pkl")
columnas_guardadas = joblib.load("columnas_examen_modelo.pkl")
nuevas = pd.read_csv("examen_ventas_nuevas.csv")

X_nuevas = nuevas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]
X_nuevas = pd.get_dummies(X_nuevas)
X_nuevas = X_nuevas.reindex(columns=columnas_guardadas, fill_value=0)

nuevas["prediccion_venta_alta"] = modelo_cargado.predict(X_nuevas)
nuevas["interpretacion_prediccion"] = nuevas["prediccion_venta_alta"].map({
    0: "Venta no alta",
    1: "Venta alta"
})

nuevas.to_csv("examen_predicciones.csv", index=False)
print("Predicciones generadas y guardadas.")

Predicciones generadas y guardadas.

In [ ]:
#¿Qué podría pasar si no usas reindex antes de predecir?
#El codigo daria un error ya que la categorio o ciudades nuevas en los datos generarian columnas diferentes a las que el algoritmo espera
#o faltarian columnas de las ciudades que no aparecieron en este lote nuevo

In [25]:
# Parte 9. Auditoria Del Modelo
nuevas["total_estimado"] = nuevas["cantidad"] * nuevas["precio_unitario"]
nuevas["venta_alta_real_estimada"] = nuevas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)
nuevas["coincide"] = nuevas["prediccion_venta_alta"] == nuevas["venta_alta_real_estimada"]

coincidencias = nuevas["coincide"].value_counts()
print("--- Coincidencias ---")
print(coincidencias)

errores_nuevos = nuevas[nuevas["coincide"] == False].copy()
if not errores_nuevos.empty:
    errores_nuevos["distancia_a_1000"] = (errores_nuevos["total_estimado"] - 1000).abs()
    print("\n--- Errores detectados ---")
    display(errores_nuevos)
else:
    print("\nNo se detectaron errores en las predicciones.")

nuevas.to_csv("examen_predicciones.csv", index=False)

--- Coincidencias ---
coincide
True     8
False    2
Name: count, dtype: int64

--- Errores detectados ---

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
6,3007,2026-08-07,Cliente G,Silla,Muebles,1,550,Tarjeta,Leon,1,Venta alta,550,0,False,450
9,3010,2026-08-07,Cliente J,Webcam,Accesorios,2,600,Tarjeta,CDMX,0,Venta no alta,1200,1,False,200

In [ ]:
#1.¿Cuántas ventas nuevas evaluaste? 10
#2.¿Cuántas fueron predichas como venta alta? 5
#3.¿Cuántas fueron predichas como venta no alta? 5
#4.¿Cuántas coincidieron con la regla manual? 8
#5.¿Cuántas no coincidieron? 2
#6.¿Qué ventas no coincidieron?
#R=La venta con el id 3007 el modelo la predijo incorrectamente como venta alta y tambien la venta con id 3010 el modelo la predijo
#incorrectamente como venta no alta
#7.¿Los errores estuvieron cerca del límite de 1000?
#R=Si hubo uno de los errores estuvo cerca del limite pero la silla estuvo muy alejada demostrando un corte de impreciso del arbol de desicion con 
#esos valores en especifico
#8.¿Qué pasó con la categoría nueva?
#R= La columna de la categoria nueva fue descatada por que no estaba en el entrenamiento y el modelo hizo la prediccion basandose unicamente en el 
#precio y cantidad
#9.¿Qué pasó con la ciudad nueva?
#R=Ocurrio lo mismo que en la categoria se ignoro sin romper la ejecucion del modelo gracias al reindex

In [ ]:
## Resumen 

#Nombre: Juan Jose Diaz Barroso
#Grupo: 9A
#Materia: Extracción de conocimiento en bases de datos
#Exactitud obtenida: 1.0
#Ventas nuevas evaluadas: 10
#Coincidencias: 8
#Errores: 2
#Conclusión breve: 
#El modelo del arbol de decision logro intervenir correctamente la regla de clasificacion basada en la cantidad y precio unitario en la mayoria
#de los casos aun que se presentaron 2 errores en datos nuevos ademas el uso de reindex demostro ser muy importante para manejar mejor los datos como 
#nuevas categorias o ciudades en el entorno productivo de prediccion